# Data Scraping and Cleaning

In [52]:
import requests
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import warnings
import tabula
import pycountry
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

warnings.filterwarnings(action = 'ignore')

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

### 1. Data Source: [ROCS](http://rocs.hu-berlin.de/viz/sgb/)

- Airport name and three-letter symbol
- Country
- Passenger flux per day
- Connected airports
- Effective distance to outbreak center
- Geodesic distance to outbreak center (km)

In [64]:
response1 = requests.get('http://rocs.hu-berlin.de/viz/sgb/airports0.95_2014/airports.json')
rocs_airport_info_df = pd.DataFrame(response1.json()['nodes'])

response2 = requests.get('http://rocs.hu-berlin.de/viz/sgb/airports0.95_2014/spt_673.json')
rocs_data_df = pd.DataFrame(response2.json())  

# Join on index
rocs_df = rocs_data_df.join(rocs_airport_info_df, how= 'outer')
rocs_df2 = rocs_df[['Dfrom', 'Dgeo', 'name', 'continent_name', 'region_name', 'country_name', 'lid', 'F',
                    'k', 'lon', 'lat']]

rocs_df2.rename(columns = {'Dfrom':'effective_dist', 'Dgeo':'geo_dist', 'name':'airport_name', 
                     'continent_name':'continent_name', 'region_name':'region_name', 'country_name':'country_name',
                    'lid':'airport_id', 'F':'ann_pass_flux', 'k':'connected_airports', 'lon':'long', 'lat':'lat'},
               inplace = True)
rocs_df2.head()

   effective_dist     geo_dist   airport_name continent_name     region_name                 country_name airport_id  ann_pass_flux  connected_airports       long        lat
0        9.626587  8111.034829    Addis Ababa         Africa  Eastern Africa                     Ethiopia        ADD      3887132.5                56.5  38.799444   8.977778
1       13.897219  7763.569189         Asmara         Africa  Eastern Africa                      Eritrea        ASM       307820.5                10.5  38.910556  15.291944
2       14.024414  9712.495427      Bujumbura         Africa  Eastern Africa                      Burundi        BJM       252165.0                 6.5  29.318611  -3.323889
3       13.695018  8990.314878  Dar es Salaam         Africa  Eastern Africa  Tanzania United Republic of        DAR      1840029.0                17.0  39.202500  -6.878056
4       13.038729  9221.694455        Entebbe         Africa  Eastern Africa                       Uganda        EBB      1079933.0                16.5  32.443611   0.042500

In [65]:
# Rename country to normalized convention 

def retrieve_country(val):
    try:
        spec = pycountry.countries.search_fuzzy(val)
        search_results = spec[0].name
    except:
        search_results = np.nan
    return search_results

rocs_df2['test_country'] = rocs_df2.country_name.map(lambda val: retrieve_country(val))

rocs_df2.test_country.isna().value_counts()

False    1240
True       52
Name: test_country, dtype: int64

In [66]:
for index, val in enumerate(rocs_df2.test_country):
    if val is np.nan:
        print(index, rocs_df2.country_name[index])

3 Tanzania United Republic of
6 Tanzania United Republic of
13 Tanzania United Republic of
19 Tanzania United Republic of
23 Congo Democratic Republic of
33 Libyan Arab Jamahiriya
46 Libyan Arab Jamahiriya
54 Libyan Arab Jamahiriya
57 Libyan Arab Jamahiriya
75 Cape Verde
90 Cape Verde
92 Cape Verde
93 Antigua and Barbuda, Leeward Islands
103 Grenada, Windward Islands
118 Saint Kitts and Nevis, Leeward Islands
121 Virgin Islands, US
122 Virgin Islands, US
123 St Maarten (Dutch Part)
527 Korea Republic of
528 Korea Republic of
549 Korea Republic of
557 Hong Kong (SAR) China
568 Korea Republic of
596 Korea Republic of
600 Korea Republic of
612 Macao (SAR) China
635 Korea Republic of
638 Korea Republic of
648 Korea Republic of
667 Korea Republic of
697 Iran Islamic Republic of
698 Iran Islamic Republic of
703 Iran Islamic Republic of
705 Iran Islamic Republic of
719 Iran Islamic Republic of
720 Iran Islamic Republic of
736 Iran Islamic Republic of
737 Iran Islamic Republic of
742 Iran Islamic Republic of
745 Iran Islamic Republic of
753 Iran Islamic Republic of
754 Iran Islamic Republic of
755 Iran Islamic Republic of
761 Iran Islamic Republic of
959 Moldova Republic of
1020 Ireland Republic of
1027 Ireland Republic of
1035 Ireland Republic of
1037 Ireland Republic of
1046 Ireland Republic of
1124 Macedonia Former Yugoslav Republic of
1290 Northern Mariana Islands (except Guam)

In [67]:
country_map = {'Tanzania United Republic of':'Tanzania',
                                   'Congo Democratic Republic of':'Congo, The Democratic Republic of the',
                                   'Libyan Arab Jamahiriya':'Libya',
                                   'Cape Verde':'Cabo Verde',
                                   'Antigua and Barbuda, Leeward Islands': 'Antigua and Barbuda',
                                   'Grenada, Windward Islands':'Grenada',
                                   'Saint Kitts and Nevis, Leeward Islands': 'Saint Kitts and Nevis',
                                   'Virgin Islands, US': 'Virgin Islands, U.S.',
                                   'St Maarten (Dutch Part)':'Sint Maarten (Dutch part)',
                                   'Korea Republic of': 'Korea, Republic of',
                                   'Hong Kong (SAR) China': 'Hong Kong',
                                   'Macao (SAR) China':'Macao',
                                   'Iran Islamic Republic of':'Iran, Islamic Republic of',
                                   'Moldova Republic of':'Moldova',
                                   'Ireland Republic of':'Ireland',
                                   'Macedonia Former Yugoslav Republic of':'North Macedonia',
                                   'Northern Mariana Islands (except Guam)':'Northern Mariana Islands'}

country_zip = list(zip(rocs_df2.country_name, rocs_df2.test_country))

for i, (CN, TC) in enumerate(country_zip):
    if TC is np.nan:
        rocs_df2.test_country[i] = country_map[CN]

rocs_df2.test_country.isna().value_counts()

False    1292
Name: test_country, dtype: int64

In [68]:
rocs_df2.head()

   effective_dist     geo_dist   airport_name continent_name     region_name                 country_name airport_id  ann_pass_flux  connected_airports       long        lat test_country
0        9.626587  8111.034829    Addis Ababa         Africa  Eastern Africa                     Ethiopia        ADD      3887132.5                56.5  38.799444   8.977778     Ethiopia
1       13.897219  7763.569189         Asmara         Africa  Eastern Africa                      Eritrea        ASM       307820.5                10.5  38.910556  15.291944      Eritrea
2       14.024414  9712.495427      Bujumbura         Africa  Eastern Africa                      Burundi        BJM       252165.0                 6.5  29.318611  -3.323889      Burundi
3       13.695018  8990.314878  Dar es Salaam         Africa  Eastern Africa  Tanzania United Republic of        DAR      1840029.0                17.0  39.202500  -6.878056     Tanzania
4       13.038729  9221.694455        Entebbe         Africa  Eastern Africa                       Uganda        EBB      1079933.0                16.5  32.443611   0.042500       Uganda

### 2. Data Source: [US Dept of Transportation](https://data.transportation.gov/Aviation/International_Report_Passengers/xgub-n9bw)
This data only provides passenger information on international US flights.

- Year, month/datetime
- US airport and foreign airport IDs
- Number of passengers

In [7]:
response = requests.get('https://data.transportation.gov/resource/xgub-n9bw.json')
airports_df = pd.DataFrame(response.json())
airports_df.head()

                  data_dte  year month usg_apt_id usg_apt usg_wac fg_apt_id fg_apt fg_wac airlineid carrier carriergroup        type scheduled charter  total
0  2019-06-01T00:00:00.000  2019     6      12478     JFK      22     12972    LHR    493     19682      VS            0  Passengers     85790       0  85790
1  2019-06-01T00:00:00.000  2019     6      12478     JFK      22     10920    CDG    427     19532      AF            0  Passengers     85324       0  85324
2  2019-06-01T00:00:00.000  2019     6      12953     LGA      22     16271    YYZ    936     19531      AC            0  Passengers     82389       0  82389
3  2019-06-01T00:00:00.000  2019     6      12478     JFK      22     12972    LHR    493     19540      BA            0  Passengers     79975       0  79975
4  2019-06-01T00:00:00.000  2019     6      12892     LAX      91     16271    YYZ    936     19531      AC            0  Passengers     73172       0  73172

In [8]:
print('Number of US Airports: ', len(airports_df.usg_apt.unique()))
print('Number of Foreign Airports: ', len(airports_df.fg_apt.unique()))

Number of US Airports:  52
Number of Foreign Airports:  132

In [9]:
airports_df.year.value_counts()

2019    1000
Name: year, dtype: int64

In [10]:
airports_df.data_dte.value_counts()

2019-06-01T00:00:00.000    1000
Name: data_dte, dtype: int64

In [11]:
airports_df.type.value_counts()

Passengers    1000
Name: type, dtype: int64

In [12]:
airports_df.scheduled = airports_df.scheduled.astype(int)
airports_df.total = airports_df.total.astype(int)

for i in range (0, len(airports_df)):
    if (airports_df.scheduled[i] == airports_df.total[i]):
        pass
    elif (airports_df.scheduled[i] != airports_df.total[i]):
        print(i, (airports_df.scheduled[i] - airports_df.total[i]))

16 -108
465 -53
521 -58

Take total passengers instead of scheduled passengers since scheduled passengers differ for at least three flights.

### 3. Data Source: [International Health Regulations SPAR Index](http://apps.who.int/gho/data/view.main.IHRSPARCTRYALLv?lang=en)
WHO International Health Regulations State Parties Self-Assessment Annual Reporting index, a combination of indicators (country-level). The latest data is available for 2018. Index values range from 0-100.

- Country
- Legislation and Financing
- IHR Coordination and National IHR Focal Point Functions
- Zoonotic Events and the Human-animal Interface
- Food Safety
- Laboratory
- Surveillance
- Human Resources
- National Health Emergency Framework
- Health Service Provision
- Risk Communication
- Points of Entry
- Chemical Events
- Radiation Emergencies

In [13]:
spar_df = pd.read_csv('../xmart.csv')
spar_df.head()

       Country Legislation and Financing; 2018 IHR Coordination and National IHR Focal Point Functions; 2018 Zoonotic Events and the Human-animal Interface; 2018 Food Safety; 2018 Laboratory; 2018 Surveillance; 2018 Human Resources; 2018 National Health Emergency Framework; 2018 Health Service Provision; 2018 Risk Communication; 2018 Points of Entry; 2018 Chemical Events; 2018 Radiation Emergencies; 2018
0  Afghanistan                              13                                                 60                                                            80                  20               40                 80                    40                                        27                             40                       20                    10                     0                          20
1      Albania                         No data                                            No data                                                       No data             No data          No data            No data               No data                                   No data                        No data                  No data               No data               No data                     No data
2      Algeria                             100                                                 90                                                            80                  80               60                 80                    80                                        53                             93                       60                    60                   100                         100
3      Andorra                              47                                                 50                                                            60                  80               67                 20                    20                                         0                             53                       60                    20                     0                           0
4       Angola                              47                                                 80                                                            80                  20               60                 90                    60                                        60                             47                       80                    40                    40                          60

In [14]:
int_cols = list(spar_df.columns)
int_cols.remove('Country')

for col in int_cols:
    for index, val in enumerate(spar_df[col]):
        if val == 'No data':
            spar_df[col][index] = np.nan
        elif val != 'No data':
            spar_df[col][index] = float(val)

spar_df['Index'] = spar_df.apply(lambda _: 0, axis=1)

for index in range(0, len(spar_df)):
    spar_df['Index'][index] = sum(spar_df.iloc[index][int_cols])/len(int_cols)
    
spar_df2 = spar_df[['Country', 'Index']]

# impute mean into 13 country entries
spar_df2.Index.fillna(spar_df2.Index.mean(), inplace= True)

spar_df2.Index.isna().value_counts()

False    194
Name: Index, dtype: int64

In [15]:
# Rename country to normalized convention 

spar_df2['test_country'] = spar_df2.Country.map(lambda val: retrieve_country(val))

spar_df2.test_country.isna().value_counts()

False    189
True       5
Name: test_country, dtype: int64

In [16]:
for index, val in enumerate(spar_df2.test_country):
    if val is np.nan:
        print(index, spar_df2.Country[index])

20 Bolivia (Plurinational State of)
47 Democratic Republic of the Congo
80 Iran (Islamic Republic of)
111 Micronesia (Federated States of)
189 Venezuela (Bolivarian Republic of)

In [17]:
country_map = {'Bolivia (Plurinational State of)':'Bolivia',
                                   'Democratic Republic of the Congo':'Congo, The Democratic Republic of the',
                                   'Libyan Arab Jamahiriya':'Libya',
                                   'Iran (Islamic Republic of)':'Iran, Islamic Republic of',
                                   'Micronesia (Federated States of)':'Micronesia, Federated States of',
                                   'Venezuela (Bolivarian Republic of)':'Venezuela, Bolivarian Republic of'}

country_zip = list(zip(spar_df2.Country, spar_df2.test_country))

for i, (CN, TC) in enumerate(country_zip):
    if TC is np.nan:
        spar_df2.test_country[i] = country_map[CN]

spar_df2.test_country.isna().value_counts()

False    194
Name: test_country, dtype: int64

### 4. Data Source: [Johns Hopkins University](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv)
Sourcing daily cumulative confirmed cases, recoveries, and deaths per location (Jan 21 - present) from:
- World Health Organization (WHO): https://www.who.int/
- DXY.cn. Pneumonia. 2020. http://3g.dxy.cn/newh5/view/pneumonia.
- BNO News: https://bnonews.com/index.php/2020/02/the-latest-coronavirus-cases/
- National Health Commission of the People’s Republic of China (NHC):
http://www.nhc.gov.cn/xcs/yqtb/list_gzbd.shtml
- China CDC (CCDC): http://weekly.chinacdc.cn/news/TrackingtheEpidemic.htm
- Hong Kong Department of Health: https://www.chp.gov.hk/en/features/102465.html
- Macau Government: https://www.ssm.gov.mo/portal/
- Taiwan CDC: https://sites.google.com/cdc.gov.tw/2019ncov/taiwan?authuser=0
- US CDC: https://www.cdc.gov/coronavirus/2019-ncov/index.html
- Government of Canada: https://www.canada.ca/en/public-health/services/diseases/coronavirus.html
- Australia Government Department of Health: https://www.health.gov.au/news/coronavirus-update-at-a-glance
- European Centre for Disease Prevention and Control (ECDC): https://www.ecdc.europa.eu/en/geographical-distribution-2019-ncov-cases
- Ministry of Health Singapore (MOH): https://www.moh.gov.sg/covid-19

In [18]:
# git pull origin master to update COVID-19 files for most recent confirmed cases
# https://github.com/CSSEGISandData/COVID-19
jhu_df = pd.read_csv('../COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv')
jhu_df.head()

  Province/State  Country/Region       Lat      Long  1/22/20  1/23/20  1/24/20  1/25/20  1/26/20  1/27/20  1/28/20  1/29/20  1/30/20  1/31/20  2/1/20  2/2/20  2/3/20  2/4/20  2/5/20  2/6/20  2/7/20  2/8/20  2/9/20  2/10/20  2/11/20  2/12/20  2/13/20  2/14/20  2/15/20  2/16/20  2/17/20  2/18/20  2/19/20  2/20/20  2/21/20  2/22/20  2/23/20
0          Anhui  Mainland China  31.82571  117.2264        1        9       15       39       60       70      106      152      200      237     297     340     408     480     530     591     665     733     779      830      860      889      910      934      950      962      973      982      986      987      988      989      989
1        Beijing  Mainland China  40.18238  116.4142       14       22       36       41       68       80       91      111      114      139     168     191     212     228     253     274     297     315     326      337      342      352      366      372      375      380      381      387      393      395      396      399      399
2      Chongqing  Mainland China  30.05718  107.8740        6        9       27       57       75      110      132      147      182      211     247     300     337     366     389     411     426     428     468      486      505      518      529      537      544      551      553      555      560      567      572      573      575
3         Fujian  Mainland China  26.07783  117.9895        1        5       10       18       35       59       80       84      101      120     144     159     179     194     205     215     224     239     250      261      267      272      279      281      285      287      290      292      293      293      293      293      293
4          Gansu  Mainland China  36.06110  103.8343        0        2        2        4        7       14       19       24       26       29      40      51      55      57      62      62      67      79      83       83       86       87       90       90       90       90       91       91       91       91       91       91       91

In [19]:
jhu_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 37 columns):
Province/State    61 non-null object
Country/Region    85 non-null object
Lat               85 non-null float64
Long              85 non-null float64
1/22/20           85 non-null int64
1/23/20           85 non-null int64
1/24/20           85 non-null int64
1/25/20           85 non-null int64
1/26/20           85 non-null int64
1/27/20           85 non-null int64
1/28/20           85 non-null int64
1/29/20           85 non-null int64
1/30/20           85 non-null int64
1/31/20           85 non-null int64
2/1/20            85 non-null int64
2/2/20            85 non-null int64
2/3/20            85 non-null int64
2/4/20            85 non-null int64
2/5/20            85 non-null int64
2/6/20            85 non-null int64
2/7/20            85 non-null int64
2/8/20            85 non-null int64
2/9/20            85 non-null int64
2/10/20           85 non-null int64
2/11/20           85 non-null int64
2/12/20           85 non-null int64
2/13/20           85 non-null int64
2/14/20           85 non-null int64
2/15/20           85 non-null int64
2/16/20           85 non-null int64
2/17/20           85 non-null int64
2/18/20           85 non-null int64
2/19/20           85 non-null int64
2/20/20           85 non-null int64
2/21/20           85 non-null int64
2/22/20           85 non-null int64
2/23/20           85 non-null int64
dtypes: float64(2), int64(33), object(2)
memory usage: 24.7+ KB

In [20]:
# Rename country to normalized convention 

jhu_df['test_country'] = jhu_df['Country/Region'].map(lambda val: retrieve_country(val))

jhu_df.test_country.isna().value_counts()

False    51
True     34
Name: test_country, dtype: int64

In [21]:
for index, val in enumerate(jhu_df.test_country):
    if val is np.nan:
        print(index, jhu_df['Country/Region'][index])

0 Mainland China
1 Mainland China
2 Mainland China
3 Mainland China
4 Mainland China
5 Mainland China
6 Mainland China
7 Mainland China
8 Mainland China
9 Mainland China
10 Mainland China
11 Mainland China
12 Mainland China
13 Mainland China
14 Mainland China
15 Mainland China
16 Mainland China
17 Mainland China
18 Mainland China
19 Mainland China
20 Mainland China
21 Mainland China
22 Mainland China
23 Mainland China
24 Mainland China
25 Mainland China
26 Mainland China
27 Mainland China
28 Mainland China
29 Mainland China
30 Mainland China
33 South Korea
38 Macau
71 Others

In [22]:
country_map = {'Mainland China':'China',
                                   'Macau':'Macao',
                                   'South Korea':'''Korea, Democratic People's Republic of''',
                                   'Others':'Others'}

country_zip = list(zip(jhu_df['Country/Region'], jhu_df.test_country))

for i, (CN, TC) in enumerate(country_zip):
    if TC is np.nan:
        jhu_df.test_country[i] = country_map[CN]

jhu_df.test_country.isna().value_counts()

False    85
Name: test_country, dtype: int64

### 5. Data Sources: 
### [UN, source = World Bank](http://data.un.org/Data.aspx?q=GDP+per+capita&d=WDI&f=Indicator_Code%3aNY.GDP.PCAP.PP.CD)

- GDP per capita for 2018, 230 country records

### [London Datastore, source = UN](https://data.london.gov.uk/dataset/global-city-population-estimates)

- City populations over 300k time series (1950-2030, 5 yr) with latitude/longitude

In [23]:
# GDP per capita, PPP (current international $)
gdp_df = pd.read_csv('../UNdata_Export_20200221_065525496.csv')
gdp_df.head()

       Country or Area  Year         Value  Value Footnotes
0          Afghanistan  2018   1955.006208              NaN
1              Albania  2018  13364.155397              NaN
2              Algeria  2018  15481.787620              NaN
3               Angola  2018   6452.355165              NaN
4  Antigua and Barbuda  2018  26868.133524              NaN

In [24]:
# Rename country to normalized convention 

gdp_df['test_country'] = gdp_df['Country or Area'].map(lambda val: retrieve_country(val))

gdp_df.test_country.isna().value_counts()

False    175
True      55
Name: test_country, dtype: int64

In [25]:
for index, val in enumerate(gdp_df.test_country):
    if val is np.nan:
        print(index, gdp_df['Country or Area'][index])

5 Arab World
27 CÃ´te d'Ivoire
32 Caribbean small states
34 Central Europe and the Baltics
43 CuraÃ§ao
45 Dem. Rep. Congo
49 Early-demographic dividend
50 East Asia & Pacific
51 East Asia & Pacific (excluding high income)
52 East Asia & Pacific (IDA & IBRD)
60 Euro area
61 Europe & Central Asia
62 Europe & Central Asia (excluding high income)
63 Europe & Central Asia (IDA & IBRD)
64 European Union
67 Fragile and conflict affected situations
80 Heavily indebted poor countries (HIPC)
81 High income
83 Hong Kong SAR, China
85 IBRD only
87 IDA & IBRD total
88 IDA blend
89 IDA only
90 IDA total
107 Lao PDR
108 Late-demographic dividend
109 Latin America & Caribbean
110 Latin America & Caribbean (excluding high income)
111 Latin America & Caribbean (IDA & IBRD)
113 Least developed countries: UN classification
119 Low & middle income
120 Low income
121 Lower middle income
123 Macao SAR, China
135 Middle East & North Africa
136 Middle income
151 North America
154 OECD members
156 Other small states
157 Pacific island small states
167 Post-demographic dividend
168 Pre-demographic dividend
174 SÃ£o TomÃ© and Principe
184 Small states
187 South Asia
188 South Asia (IDA & IBRD)
191 St. Kitts and Nevis
192 St. Lucia
193 St. Vincent and the Grenadines
194 Sub-Saharan Africa
195 Sub-Saharan Africa (excluding high income)
196 Sub-Saharan Africa (IDA & IBRD)
220 Upper middle income
225 West Bank and Gaza
226 World

In [26]:
# There are 195 countries in the world according to Google, but we have 230 here! 
# Much of this is extraneous and can be dropped. Some country renaming to be done.

gdp_df = gdp_df.drop(labels=[5, 32, 34, 49, 50, 51, 52, 60, 61, 62, 63, 64, 67, 80, 81, 85, 87, 88, 89, 90,
                  108, 109, 110, 111, 113, 119, 120, 121, 135, 136, 151, 154, 156, 157, 167,
                  168, 184, 187, 188, 194, 195, 196, 220, 226], axis = 0).reset_index()

country_map = {'''CÃ´te d'Ivoire''':'''Côte d'Ivoire''',
               'CuraÃ§ao':'Curaçao',
               'Dem. Rep. Congo':'Congo, The Democratic Republic of the',
               'Hong Kong SAR, China':'Hong Kong',
               'Lao PDR':"Lao People's Democratic Republic",
              'Macao SAR, China':'Macao',
              'SÃ£o TomÃ© and Principe':'Sao Tome and Principe',
              'St. Kitts and Nevis':'Saint Kitts and Nevis',
              'St. Lucia':'Saint Lucia',
              'St. Vincent and the Grenadines':'Saint Vincent and the Grenadines',
              'West Bank and Gaza':'Palestine, State of'}

country_zip = list(zip(gdp_df['Country or Area'], gdp_df.test_country))

for i, (CN, TC) in enumerate(country_zip):
    if TC is np.nan:
        gdp_df.test_country[i] = country_map[CN]

gdp_df.test_country.isna().value_counts()

False    186
Name: test_country, dtype: int64

In [27]:
city_pop_df = pd.read_excel('../global-city-population-estimates.xls', sheet_name=1)
city_pop_df.head()

   Country Code Country or area  City Code Urban Agglomeration   Note   Latitude   Longitude       1950       1955       1960       1965       1970       1975       1980       1985       1990       1995       2000       2005       2010       2015       2020       2025       2030
0           392           Japan      21671               Tokyo  325.0  35.689500  139.691710  11274.641  13712.679  16678.821  20284.371  23297.503  26614.733  28548.512  30303.794  32530.003  33586.573  34449.908  35621.544  36833.979  38001.018  38323.229  37875.951  37190.489
1           356           India      21228               Delhi  318.0  28.666670   77.216670   1369.369   1781.624   2282.962   2845.042   3530.693   4425.964   5558.481   7325.185   9725.885  12407.372  15732.304  18670.494  21935.142  25703.168  29347.622  32726.564  36060.100
2           156           China      20656            Shanghai  202.0  31.222220  121.458060   4300.942   5846.383   6819.634   6428.131   6036.492   5626.640   5966.171   6846.765   7823.028  10449.535  13958.981  16763.455  19979.977  23740.778  27137.316  29441.569  30750.671
3            76          Brazil      20287           São Paulo    NaN -23.547500  -46.636110   2334.038   3043.828   3969.759   5494.150   7620.490   9614.016  12089.454  13394.815  14775.840  15913.473  17014.078  18288.134  19659.808  21066.245  22118.900  22899.066  23444.363
4           356           India      21206     Mumbai (Bombay)    NaN  19.073975   72.880838   2857.359   3432.147   4060.373   4853.571   5811.304   7081.960   8657.886  10390.912  12436.423  14309.845  16366.787  17890.736  19421.983  21042.538  22838.483  25207.329  27796.555

In [28]:
# Rename country to normalized convention 

city_pop_df['test_country'] = city_pop_df['Country or area'].map(lambda val: retrieve_country(val))

city_pop_df.test_country.isna().value_counts()

False    1619
True       73
Name: test_country, dtype: int64

In [29]:
for index, val in enumerate(city_pop_df.test_country):
    if val is np.nan:
        print(index, city_pop_df['Country or area'][index])

22 Democratic Republic of the Congo
39 Iran (Islamic Republic of)
45 China, Hong Kong SAR
142 Iran (Islamic Republic of)
149 Venezuela (Bolivarian Republic of)
153 Dem. People's Republic of Korea
206 Venezuela (Bolivarian Republic of)
219 Bolivia (Plurinational State of)
227 Democratic Republic of the Congo
229 Democratic Republic of the Congo
252 Iran (Islamic Republic of)
257 Bolivia (Plurinational State of)
259 Iran (Islamic Republic of)
271 Venezuela (Bolivarian Republic of)
286 Iran (Islamic Republic of)
304 Iran (Islamic Republic of)
380 Bolivia (Plurinational State of)
389 Iran (Islamic Republic of)
392 Iran (Islamic Republic of)
407 Democratic Republic of the Congo
410 Venezuela (Bolivarian Republic of)
471 Democratic Republic of the Congo
473 Venezuela (Bolivarian Republic of)
562 Iran (Islamic Republic of)
607 Democratic Republic of the Congo
676 Iran (Islamic Republic of)
710 Venezuela (Bolivarian Republic of)
712 Iran (Islamic Republic of)
730 Venezuela (Bolivarian Republic of)
741 Democratic Republic of the Congo
805 Dem. People's Republic of Korea
886 China, Macao SAR
903 Dem. People's Republic of Korea
924 Iran (Islamic Republic of)
931 Venezuela (Bolivarian Republic of)
937 Iran (Islamic Republic of)
949 Iran (Islamic Republic of)
963 Iran (Islamic Republic of)
970 Iran (Islamic Republic of)
1007 Iran (Islamic Republic of)
1035 TFYR Macedonia
1053 Democratic Republic of the Congo
1074 Democratic Republic of the Congo
1078 Iran (Islamic Republic of)
1081 Democratic Republic of the Congo
1090 Democratic Republic of the Congo
1163 Democratic Republic of the Congo
1198 Democratic Republic of the Congo
1211 Iran (Islamic Republic of)
1225 Iran (Islamic Republic of)
1234 Iran (Islamic Republic of)
1268 Iran (Islamic Republic of)
1317 Venezuela (Bolivarian Republic of)
1342 Venezuela (Bolivarian Republic of)
1351 Iran (Islamic Republic of)
1356 Democratic Republic of the Congo
1368 Bolivia (Plurinational State of)
1377 Venezuela (Bolivarian Republic of)
1389 Venezuela (Bolivarian Republic of)
1424 Iran (Islamic Republic of)
1433 Venezuela (Bolivarian Republic of)
1468 Venezuela (Bolivarian Republic of)
1478 Iran (Islamic Republic of)
1499 Dem. People's Republic of Korea
1519 Democratic Republic of the Congo
1522 Venezuela (Bolivarian Republic of)
1538 Venezuela (Bolivarian Republic of)
1551 Iran (Islamic Republic of)
1577 Dem. People's Republic of Korea
1583 Iran (Islamic Republic of)
1588 Venezuela (Bolivarian Republic of)
1604 Venezuela (Bolivarian Republic of)
1673 Venezuela (Bolivarian Republic of)

In [30]:
country_map = {'Democratic Republic of the Congo':'Congo, The Democratic Republic of the',
               'Iran (Islamic Republic of)':'Iran, Islamic Republic of',
              'China, Hong Kong SAR':'Hong Kong',
               'Venezuela (Bolivarian Republic of)':"Venezuela, Bolivarian Republic of",
              '''Dem. People's Republic of Korea''':"Korea, Democratic People's Republic of",
              'Bolivia (Plurinational State of)':'Bolivia, Plurinational State of',
              'China, Macao SAR':'Macao',
              'TFYR Macedonia':'North Macedonia'}

country_zip = list(zip(city_pop_df['Country or area'], city_pop_df.test_country))

for i, (CN, TC) in enumerate(country_zip):
    if TC is np.nan:
        city_pop_df.test_country[i] = country_map[CN]

city_pop_df.test_country.isna().value_counts()

False    1692
Name: test_country, dtype: int64

In [31]:
# City/lat/long stuff here

### 5. Data Source: World Bank

[Doctors](https://data.worldbank.org/indicator/SH.MED.PHYS.ZS) and [hospital beds per 1000 people/country](https://data.worldbank.org/indicator/SH.MED.BEDS.ZS)

In [32]:
doctors_df = pd.read_csv('../API_SH.MED.PHYS.ZS_DS2_en_csv_v2_713164/API_SH.MED.PHYS.ZS_DS2_en_csv_v2_713164.csv', 
                         skiprows=4)
doctors_df.head()

  Country Name Country Code                 Indicator Name  Indicator Code   1960  1961  1962  1963  1964   1965  1966  1967  1968  1969   1970   1971   1972  1973  1974  1975  1976   1977  1978  1979   1980   1981  1982   1983   1984   1985   1986   1987  1988   1989   1990  1991  1992   1993  1994   1995   1996    1997   1998   1999   2000    2001   2002    2003    2004  2005   2006    2007    2008    2009    2010    2011    2012    2013    2014    2015    2016    2017  2018  2019  Unnamed: 64
0        Aruba          ABW  Physicians (per 1,000 people)  SH.MED.PHYS.ZS    NaN   NaN   NaN   NaN   NaN    NaN   NaN   NaN   NaN   NaN    NaN    NaN    NaN   NaN   NaN   NaN   NaN    NaN   NaN   NaN    NaN    NaN   NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN   NaN   NaN    NaN   NaN  1.120    NaN     NaN    NaN    NaN    NaN     NaN    NaN     NaN     NaN   NaN    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   NaN   NaN          NaN
1  Afghanistan          AFG  Physicians (per 1,000 people)  SH.MED.PHYS.ZS  0.035   NaN   NaN   NaN   NaN  0.063   NaN   NaN   NaN   NaN  0.065    NaN    NaN   NaN   NaN   NaN   NaN    NaN   NaN   NaN    NaN  0.077   NaN    NaN    NaN    NaN  0.183  0.179   NaN  0.129  0.109   NaN   NaN  0.143   NaN    NaN    NaN  0.1100    NaN    NaN    NaN  0.1957    NaN     NaN     NaN   NaN  0.163  0.1774  0.1771  0.2156  0.2396  0.2553  0.2450  0.2894  0.3039  0.2907  0.2840     NaN   NaN   NaN          NaN
2       Angola          AGO  Physicians (per 1,000 people)  SH.MED.PHYS.ZS  0.067   NaN   NaN   NaN   NaN  0.076   NaN   NaN   NaN   NaN  0.116    NaN    NaN   NaN   NaN   NaN   NaN    NaN   NaN   NaN    NaN    NaN   NaN    NaN  0.059    NaN    NaN    NaN   NaN    NaN  0.042   NaN   NaN    NaN   NaN    NaN    NaN  0.0584    NaN    NaN    NaN     NaN    NaN     NaN  0.0618   NaN    NaN     NaN     NaN  0.1311     NaN     NaN     NaN     NaN     NaN     NaN     NaN  0.2149   NaN   NaN          NaN
3      Albania          ALB  Physicians (per 1,000 people)  SH.MED.PHYS.ZS  0.276   NaN   NaN   NaN   NaN  0.481   NaN   NaN   NaN   NaN  0.739  0.911  0.845   NaN   NaN   NaN   NaN  1.036   NaN   NaN  1.367    NaN   NaN  1.415  1.407  1.406    NaN    NaN   NaN  1.403  1.374  1.47  1.65  1.425   NaN  1.306  1.354  1.2950  1.289  1.282  1.389     NaN  1.305     NaN     NaN   NaN    NaN  1.1460     NaN  1.1440  1.2379  1.2225  1.2658  1.2706     NaN     NaN  1.1998     NaN   NaN   NaN          NaN
4      Andorra          AND  Physicians (per 1,000 people)  SH.MED.PHYS.ZS    NaN   NaN   NaN   NaN   NaN    NaN   NaN   NaN   NaN   NaN    NaN    NaN    NaN   NaN   NaN   NaN   NaN    NaN   NaN   NaN    NaN    NaN   NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN   NaN   NaN    NaN   NaN  2.231    NaN  2.4350  2.470  2.594  2.549  2.5940    NaN  3.3333     NaN   NaN  3.640  3.7160     NaN  3.1120  4.0000     NaN     NaN     NaN     NaN  3.3333     NaN     NaN   NaN   NaN          NaN

In [33]:
doctors_df['latest_doctors_per_1000'] = doctors_df.ffill(axis=1).iloc[:, -1] 

for index, val in enumerate(doctors_df.latest_doctors_per_1000):
    if val == 'SH.MED.PHYS.ZS':
        doctors_df.latest_doctors_per_1000[index] = np.nan
    else:
        doctors_df.latest_doctors_per_1000[index] = float(val)

# impute median into 11 country entries
doctors_df.latest_doctors_per_1000.fillna(doctors_df.latest_doctors_per_1000.median(), inplace = True)

doctors_df.latest_doctors_per_1000.isna().value_counts()

False    264
Name: latest_doctors_per_1000, dtype: int64

In [34]:
hosp_beds_df = pd.read_csv('../API_SH.MED.BEDS.ZS_DS2_en_csv_v2_717551/API_SH.MED.BEDS.ZS_DS2_en_csv_v2_717551.csv', 
                           skiprows=4)
hosp_beds_df.head()

  Country Name Country Code                    Indicator Name  Indicator Code      1960  1961  1962  1963  1964  1965  1966  1967  1968  1969   1970  1971  1972  1973  1974  1975  1976  1977  1978  1979    1980    1981    1982    1983   1984    1985    1986    1987    1988    1989    1990    1991    1992    1993    1994  1995  1996  1997  1998  1999  2000  2001  2002  2003  2004  2005  2006  2007  2008  2009  2010  2011  2012  2013  2014  2015  2016  2017  2018  2019  Unnamed: 64
0        Aruba          ABW  Hospital beds (per 1,000 people)  SH.MED.BEDS.ZS       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     NaN     NaN     NaN     NaN    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN
1  Afghanistan          AFG  Hospital beds (per 1,000 people)  SH.MED.BEDS.ZS  0.170627   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  0.199   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     NaN  0.2756     NaN     NaN    NaN     NaN     NaN  0.3091     NaN     NaN  0.2498     NaN     NaN     NaN     NaN   NaN   NaN   NaN   NaN   NaN   0.3  0.40   0.4   0.4   0.4   0.4   0.4   0.4   0.4   0.4   0.4   0.4   0.5   0.5   0.5   0.5   NaN   NaN   NaN   NaN          NaN
2       Angola          AGO  Hospital beds (per 1,000 people)  SH.MED.BEDS.ZS  2.061462   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  2.721   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     NaN     NaN     NaN     NaN    NaN     NaN     NaN     NaN     NaN     NaN  1.2913     NaN     NaN     NaN     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   0.8   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN
3      Albania          ALB  Hospital beds (per 1,000 people)  SH.MED.BEDS.ZS  5.102676   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  4.2717  4.1871  4.1607  4.0862  4.139  4.1388  4.0697  3.9700  3.9355  4.1321  4.0249  3.9987  4.0134  3.8314  3.0171  3.19  3.14  3.05  3.05  3.03   3.3  3.30   3.1   3.1   3.0   3.1   3.1   3.1   NaN   2.8   3.0   2.6   2.9   2.9   NaN   NaN   NaN   NaN   NaN   NaN          NaN
4      Andorra          AND  Hospital beds (per 1,000 people)  SH.MED.BEDS.ZS       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     NaN     NaN     NaN     NaN    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   NaN  3.18  3.00  3.09  3.20   3.2  2.59   NaN   3.3   NaN   2.7   2.6   2.6   NaN   2.5   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN

In [35]:
hosp_beds_df['latest_hosp_beds_per_1000'] = hosp_beds_df.ffill(axis=1).iloc[:, -1] 

for index, val in enumerate(hosp_beds_df.latest_hosp_beds_per_1000):
    if val == 'SH.MED.BEDS.ZS':
        hosp_beds_df.latest_hosp_beds_per_1000[index] = np.nan
    else:
        hosp_beds_df.latest_hosp_beds_per_1000[index] = float(val)

# impute median into 18 country entries
hosp_beds_df.latest_hosp_beds_per_1000.fillna(hosp_beds_df.latest_hosp_beds_per_1000.median(), inplace = True)

hosp_beds_df.latest_hosp_beds_per_1000.isna().value_counts()

False    264
Name: latest_hosp_beds_per_1000, dtype: int64

### 6. Begin merging country-level data

- SPAR index
- GDP per capita
- Physicians per 1000 people
- Hospital beds per 100 people

In [36]:
health_df = hosp_beds_df[['Country Name', 
                          'latest_hosp_beds_per_1000']].merge(doctors_df[['Country Name',
                                                                        'latest_doctors_per_1000']], 
                                                             how = 'inner', 
                                                             on = 'Country Name')

In [37]:
# Rename country to normalized convention 

health_df['test_country'] = health_df['Country Name'].map(lambda val: retrieve_country(val))

health_df.test_country.isna().value_counts()

False    196
True      68
Name: test_country, dtype: int64

In [38]:
for index, val in enumerate(health_df.test_country):
    if val is np.nan:
        print(index, health_df['Country Name'][index])

5 Arab World
21 Bahamas, The
34 Central Europe and the Baltics
36 Channel Islands
41 Congo, Dem. Rep.
42 Congo, Rep.
47 Caribbean small states
59 East Asia & Pacific (excluding high income)
60 Early-demographic dividend
61 East Asia & Pacific
62 Europe & Central Asia (excluding high income)
63 Europe & Central Asia
65 Egypt, Arab Rep.
66 Euro area
71 European Union
72 Fragile and conflict affected situations
77 Micronesia, Fed. Sts.
84 Gambia, The
93 High income
94 Hong Kong SAR, China
96 Heavily indebted poor countries (HIPC)
100 IBRD only
101 IDA & IBRD total
102 IDA total
103 IDA blend
105 IDA only
108 Not classified
110 Iran, Islamic Rep.
123 St. Kitts and Nevis
124 Korea, Rep.
126 Latin America & Caribbean (excluding high income)
127 Lao PDR
131 St. Lucia
132 Latin America & Caribbean
133 Least developed countries: UN classification
134 Low income
137 Lower middle income
138 Low & middle income
140 Late-demographic dividend
144 Macao SAR, China
145 St. Martin (French part)
151 Middle East & North Africa
154 Middle income
159 Middle East & North Africa (excluding high income)
168 North America
179 OECD members
181 Other small states
189 Pre-demographic dividend
191 Korea, Dem. People’s Rep.
194 West Bank and Gaza
195 Pacific island small states
196 Post-demographic dividend
202 South Asia
213 Sub-Saharan Africa (excluding high income)
215 Sub-Saharan Africa
216 Small states
228 East Asia & Pacific (IDA & IBRD countries)
229 Europe & Central Asia (IDA & IBRD countries)
234 Latin America & the Caribbean (IDA & IBRD countries)
236 Middle East & North Africa (IDA & IBRD countries)
238 South Asia (IDA & IBRD)
239 Sub-Saharan Africa (IDA & IBRD countries)
247 Upper middle income
251 St. Vincent and the Grenadines
252 Venezuela, RB
254 Virgin Islands (U.S.)
257 World
260 Yemen, Rep.

In [39]:
health_df = health_df.drop(labels=[5, 34, 47, 59, 60, 61, 62, 63, 66, 71, 72, 93, 96, 100, 
                                   101, 102, 103, 105, 126, 132, 133, 134, 137, 138, 140, 151, 
                                   154, 159, 168, 179, 181, 189, 195, 196, 202, 213, 215, 216,
                                   228, 229, 234, 236, 238, 239, 247, 257], 
                           axis = 0).reset_index()

country_map = {'Congo, Dem. Rep.':'Congo, The Democratic Republic of the',
               'Congo, Rep.':'Congo',
              'St. Vincent and the Grenadines':'Saint Vincent and the Grenadines',
               'Venezuela, RB':"Venezuela, Bolivarian Republic of",
              'West Bank and Gaza':"Palestine, State of",
              'Bolivia (Plurinational State of)':'Bolivia, Plurinational State of',
              'Virgin Islands (U.S.)':'Virgin Islands, U.S.',
              'Yemen, Rep.':'Yemen',
              'Korea, Dem. People’s Rep.':"Korea, Democratic People's Republic of",
              'St. Martin (French part)':'Saint Martin (French part)',
              'Macao SAR, China':'Macao',
              'St. Lucia':'Saint Lucia',
              'Lao PDR':"Lao People's Democratic Republic",
              'Korea, Rep.':'Korea, Republic of',
              'St. Kitts and Nevis':'Saint Kitts and Nevis',
              'Iran, Islamic Rep.':'Iran, Islamic Republic of',
              'Hong Kong SAR, China':'Hong Kong',
              'Gambia, The':'Gambia',
              'Micronesia, Fed. Sts.':'Micronesia, Federated States of',
              'Egypt, Arab Rep.':'Egypt',
              'Bahamas, The':'Bahamas', 
              'Not classified': 'Others',
              'Channel Islands':'Channel Islands'}

country_zip = list(zip(health_df['Country Name'], health_df.test_country))

for i, (CN, TC) in enumerate(country_zip):
    if TC is np.nan:
        health_df.test_country[i] = country_map[CN]

health_df.test_country.isna().value_counts()

False    218
Name: test_country, dtype: int64

In [40]:
gdp_df.rename(columns={'test_country': 'test_country', 'Value': 'GDP_per_capita'}, inplace = True)

country_stats_df = health_df.merge(gdp_df[['test_country', 'GDP_per_capita']], how = 'outer', on = 'test_country')

spar_df2.rename(columns = {'test_country': 'test_country', 'Index': 'SPAR_index'}, inplace = True)
country_stats_df = country_stats_df.merge(spar_df2, how = 'outer', on = 'test_country')

# impute median SPAR index for 112 country entries
country_stats_df.SPAR_index.fillna(country_stats_df.SPAR_index.median(), inplace = True)

# impute median GDP into 51 country entries
country_stats_df.GDP_per_capita.fillna(country_stats_df.GDP_per_capita.median(), inplace = True)

# impute median hosp beds and physicians into 17 country entries
country_stats_df.latest_hosp_beds_per_1000.fillna(country_stats_df.latest_hosp_beds_per_1000.median(), inplace = True)
country_stats_df.latest_doctors_per_1000.fillna(country_stats_df.latest_doctors_per_1000.median(), inplace = True)

country_stats_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 231 entries, 0 to 230
Data columns (total 8 columns):
index                        227 non-null float64
Country Name                 227 non-null object
latest_hosp_beds_per_1000    231 non-null float64
latest_doctors_per_1000      231 non-null float64
test_country                 231 non-null object
GDP_per_capita               231 non-null float64
Country                      204 non-null object
SPAR_index                   231 non-null float64
dtypes: float64(5), object(3)
memory usage: 16.2+ KB

### 7. Data Source: [Rand Corporation](https://www.rand.org/pubs/research_reports/RR1605.html)

Infectious Disease Vulnerability Index (IDVI) takes data from various international organizations to determine scores per each of seven domains as well as an overall score. The domain categories are:
- Demographic
- Health Care
- Public Health
- Disease Dynamics
- Political-Domestic
- Political-International
- Economic

In [41]:
IVDI_df = pd.read_csv('../Rand_IVDF.csv', sep = ' ', quotechar = "'")
IVDI_df.head()

                       Rank Country or Territory  Combatant Command Overall Score  Normed Demographic Domain Score  Health Care Domain Score  Public Health Domain Score  Disease Dynamics Domain Score  Political- Domestic Domain Score  Political- International Domain Score  Economic Domain Score
1                   Somalia              AFRICOM                         0.000000                         0.348761                  0.058301                    0.000000                       0.629775                          0.000000                               0.102937               0.075656
2  Central African Republic              AFRICOM                         0.000061                         0.155293                  0.000000                    0.045047                       0.548853                          0.053251                               0.315859               0.005424
3                      Chad              AFRICOM                         0.098450                         0.210246                  0.049051                    0.188812                       0.543405                          0.115587                               0.259991               0.106760
4               South Sudan              AFRICOM                         0.100836                         0.007305                  0.231602                    0.189689                       0.415040                          0.084988                               0.355877               0.186605
5                Mauritania              AFRICOM                         0.107294                         0.303530                  0.200198                    0.013730                       0.542587                          0.199660                               0.267845               0.219330

In [42]:
cols_to_avg = list(IVDI_df.columns)
cols_to_avg.remove('Rank')
cols_to_avg.remove('Country or Territory')
cols_to_avg

['Combatant Command Overall Score',
 'Normed Demographic Domain Score',
 'Health Care Domain Score',
 'Public Health Domain Score',
 'Disease Dynamics Domain Score',
 'Political- Domestic Domain Score',
 'Political- International Domain Score',
 'Economic Domain Score']

In [43]:
IVDI_df[cols_to_avg] = IVDI_df[cols_to_avg].astype(float)

In [44]:
IVDI_df['Overall Score'] = 0
IVDI_df['Overall Score'] = IVDI_df[cols_to_avg].mean(axis=1)

IVDI_df.head()

                       Rank Country or Territory  Combatant Command Overall Score  Normed Demographic Domain Score  Health Care Domain Score  Public Health Domain Score  Disease Dynamics Domain Score  Political- Domestic Domain Score  Political- International Domain Score  Economic Domain Score  Overall Score
1                   Somalia              AFRICOM                         0.000000                         0.348761                  0.058301                    0.000000                       0.629775                          0.000000                               0.102937               0.075656       0.151929
2  Central African Republic              AFRICOM                         0.000061                         0.155293                  0.000000                    0.045047                       0.548853                          0.053251                               0.315859               0.005424       0.140473
3                      Chad              AFRICOM                         0.098450                         0.210246                  0.049051                    0.188812                       0.543405                          0.115587                               0.259991               0.106760       0.196538
4               South Sudan              AFRICOM                         0.100836                         0.007305                  0.231602                    0.189689                       0.415040                          0.084988                               0.355877               0.186605       0.196493
5                Mauritania              AFRICOM                         0.107294                         0.303530                  0.200198                    0.013730                       0.542587                          0.199660                               0.267845               0.219330       0.231772

In [45]:
IVDI_df = IVDI_df[['Rank', 'Overall Score']]
IVDI_df.rename(columns = {'Rank': 'Country Name', 'Overall Score': 'IVDI_score'}, inplace = True)
IVDI_df.head()

               Country Name  IVDI_score
1                   Somalia    0.151929
2  Central African Republic    0.140473
3                      Chad    0.196538
4               South Sudan    0.196493
5                Mauritania    0.231772

In [46]:
IVDI_df['test_country'] = IVDI_df['Country Name'].map(lambda val: retrieve_country(val))

IVDI_df.test_country.isna().value_counts()

False    187
True       8
Name: test_country, dtype: int64

In [47]:
IVDI_df = IVDI_df.reset_index()

In [48]:
for index, val in enumerate(IVDI_df.test_country):
    if val is np.nan:
        print(index, IVDI_df['Country Name'][index])

10 Democratic Republic of the Congo
25 Republic of the Congo (CongoBrazzaville)
27 Côte d’Ivoire
39 Laos
42 Swaziland
45 Democratic People’s Republic of Korea (North Korea)
64 Cape Verde
178 Republic of Korea (South Korea)

In [49]:
country_map = {'Democratic Republic of the Congo':'Congo, The Democratic Republic of the',
               'Republic of the Congo (CongoBrazzaville)':'Congo',
              'Côte d’Ivoire':"Côte d'Ivoire",
               'Laos':"Lao People's Democratic Republic",
              'Swaziland':'Eswatini',
              'Democratic People’s Republic of Korea (North Korea)':"Korea, Democratic People's Republic of",
              'Cape Verde':'Cabo Verde',
              'Republic of Korea (South Korea)':'Korea, Republic of'}

country_zip = list(zip(IVDI_df['Country Name'], IVDI_df.test_country))

for i, (CN, TC) in enumerate(country_zip):
    if TC is np.nan:
        IVDI_df.test_country[i] = country_map[CN]

IVDI_df.test_country.isna().value_counts()

False    195
Name: test_country, dtype: int64

### 8. Continue merging country-level data

- country_stats
    - SPAR index
    - GDP per capita
    - Physicians per 1000 people
    - Hospital beds per 100 people
- IVDI

In [50]:
country_df = country_stats_df = country_stats_df.merge(IVDI_df[['test_country', 'IVDI_score']], how = 'outer', on = 'test_country')
country_df.drop(columns=['Country Name', 'Country', 'index'], inplace=True)
country_df.head()

   latest_hosp_beds_per_1000  latest_doctors_per_1000 test_country  GDP_per_capita  SPAR_index  IVDI_score
0                   2.400337                   1.1200        Aruba    13536.794829   60.463238         NaN
1                   0.500000                   0.2840  Afghanistan     1955.006208   34.000000    0.257002
2                   0.800000                   0.2149       Angola     6452.355165   58.769231    0.279402
3                   2.900000                   1.1998      Albania    13364.155397   60.463238    0.636599
4                   2.500000                   3.3333      Andorra    13536.794829   36.692308    0.679377

In [51]:
country_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 244 entries, 0 to 243
Data columns (total 6 columns):
latest_hosp_beds_per_1000    243 non-null float64
latest_doctors_per_1000      243 non-null float64
test_country                 244 non-null object
GDP_per_capita               243 non-null float64
SPAR_index                   243 non-null float64
IVDI_score                   217 non-null float64
dtypes: float64(5), object(1)
memory usage: 13.3+ KB

### 9. Look at latitude/longitude using geopy to normalize locations

- City population densities
- JHU: provinces/states with confirmed coronavirus cases
- ROCS: airport nodes

In [55]:
city_pop_df = city_pop_df[['test_country','Urban Agglomeration', 
                           'Latitude', 'Longitude', '2020']]
city_pop_df.head()

  test_country Urban Agglomeration   Latitude   Longitude       2020
0        Japan               Tokyo  35.689500  139.691710  38323.229
1        India               Delhi  28.666670   77.216670  29347.622
2        China            Shanghai  31.222220  121.458060  27137.316
3       Brazil           São Paulo -23.547500  -46.636110  22118.900
4        India     Mumbai (Bombay)  19.073975   72.880838  22838.483

In [69]:
rocs_df2.drop(columns = 'country_name', inplace = True)
rocs_df2.head()

   effective_dist     geo_dist   airport_name continent_name     region_name airport_id  ann_pass_flux  connected_airports       long        lat test_country
0        9.626587  8111.034829    Addis Ababa         Africa  Eastern Africa        ADD      3887132.5                56.5  38.799444   8.977778     Ethiopia
1       13.897219  7763.569189         Asmara         Africa  Eastern Africa        ASM       307820.5                10.5  38.910556  15.291944      Eritrea
2       14.024414  9712.495427      Bujumbura         Africa  Eastern Africa        BJM       252165.0                 6.5  29.318611  -3.323889      Burundi
3       13.695018  8990.314878  Dar es Salaam         Africa  Eastern Africa        DAR      1840029.0                17.0  39.202500  -6.878056     Tanzania
4       13.038729  9221.694455        Entebbe         Africa  Eastern Africa        EBB      1079933.0                16.5  32.443611   0.042500       Uganda

In [71]:
jhu_df.drop(columns = 'Country/Region', inplace = True)
jhu_df.head()

  Province/State       Lat      Long  1/22/20  1/23/20  1/24/20  1/25/20  1/26/20  1/27/20  1/28/20  1/29/20  1/30/20  1/31/20  2/1/20  2/2/20  2/3/20  2/4/20  2/5/20  2/6/20  2/7/20  2/8/20  2/9/20  2/10/20  2/11/20  2/12/20  2/13/20  2/14/20  2/15/20  2/16/20  2/17/20  2/18/20  2/19/20  2/20/20  2/21/20  2/22/20  2/23/20 test_country
0          Anhui  31.82571  117.2264        1        9       15       39       60       70      106      152      200      237     297     340     408     480     530     591     665     733     779      830      860      889      910      934      950      962      973      982      986      987      988      989      989        China
1        Beijing  40.18238  116.4142       14       22       36       41       68       80       91      111      114      139     168     191     212     228     253     274     297     315     326      337      342      352      366      372      375      380      381      387      393      395      396      399      399        China
2      Chongqing  30.05718  107.8740        6        9       27       57       75      110      132      147      182      211     247     300     337     366     389     411     426     428     468      486      505      518      529      537      544      551      553      555      560      567      572      573      575        China
3         Fujian  26.07783  117.9895        1        5       10       18       35       59       80       84      101      120     144     159     179     194     205     215     224     239     250      261      267      272      279      281      285      287      290      292      293      293      293      293      293        China
4          Gansu  36.06110  103.8343        0        2        2        4        7       14       19       24       26       29      40      51      55      57      62      62      67      79      83       83       86       87       90       90       90       90       91       91       91       91       91       91       91        China

In [193]:
geolocator = Nominatim(user_agent="apple.chrome", timeout=10)
rgeocode = RateLimiter(geolocator.reverse, min_delay_seconds=0.01)

In [103]:
jhu_df['lat_long'] = jhu_df.Lat.map(str) + ',' + jhu_df.Long.map(str)
jhu_df.head()

  Province/State       Lat      Long  1/22/20  1/23/20  1/24/20  1/25/20  1/26/20  1/27/20  1/28/20  1/29/20  1/30/20  1/31/20  2/1/20  2/2/20  2/3/20  2/4/20  2/5/20  2/6/20  2/7/20  2/8/20  2/9/20  2/10/20  2/11/20  2/12/20  2/13/20  2/14/20  2/15/20  2/16/20  2/17/20  2/18/20  2/19/20  2/20/20  2/21/20  2/22/20  2/23/20 test_country                     lat_long
0          Anhui  31.82571  117.2264        1        9       15       39       60       70      106      152      200      237     297     340     408     480     530     591     665     733     779      830      860      889      910      934      950      962      973      982      986      987      988      989      989        China  31.825709999999997,117.2264
1        Beijing  40.18238  116.4142       14       22       36       41       68       80       91      111      114      139     168     191     212     228     253     274     297     315     326      337      342      352      366      372      375      380      381      387      393      395      396      399      399        China            40.18238,116.4142
2      Chongqing  30.05718  107.8740        6        9       27       57       75      110      132      147      182      211     247     300     337     366     389     411     426     428     468      486      505      518      529      537      544      551      553      555      560      567      572      573      575        China             30.05718,107.874
3         Fujian  26.07783  117.9895        1        5       10       18       35       59       80       84      101      120     144     159     179     194     205     215     224     239     250      261      267      272      279      281      285      287      290      292      293      293      293      293      293        China            26.07783,117.9895
4          Gansu  36.06110  103.8343        0        2        2        4        7       14       19       24       26       29      40      51      55      57      62      62      67      79      83       83       86       87       90       90       90       90       91       91       91       91       91       91       91        China             36.0611,103.8343

In [184]:
def city_county_state(coord):
    location = rgeocode(coord, language = 'en')
    try:
        county = location.raw['address']['county']
    except:
        county = ''
    try:
        state = location.raw['address']['state']
    except:
        state = ''
    try:     
        city = location.raw['address']['city']
    except:   
        city = ''
    return f'{city}, {county}, {state}'

jhu_df['city_county_state'] = jhu_df['lat_long'].apply(city_county_state)
                                                   
jhu_df.head()

  Province/State       Lat      Long  1/22/20  1/23/20  1/24/20  1/25/20  1/26/20  1/27/20  1/28/20  1/29/20  1/30/20  1/31/20  2/1/20  2/2/20  2/3/20  2/4/20  2/5/20  2/6/20  2/7/20  2/8/20  2/9/20  2/10/20  2/11/20  2/12/20  2/13/20  2/14/20  2/15/20  2/16/20  2/17/20  2/18/20  2/19/20  2/20/20  2/21/20  2/22/20  2/23/20 test_country                     lat_long                                               city      state state_city                                       state_county                                  city_county_state
0          Anhui  31.82571  117.2264        1        9       15       39       60       70      106      152      200      237     297     340     408     480     530     591     665     733     779      830      860      889      910      934      950      962      973      982      986      987      988      989      989        China  31.825709999999997,117.2264                                  Lianhua Community      Anhui                          (Lianhua Community, 合肥政务文化新区, Anhui)                 Lianhua Community, 合肥政务文化新区, Anhui
1        Beijing  40.18238  116.4142       14       22       36       41       68       80       91      111      114      139     168     191     212     228     253     274     297     315     326      337      342      352      366      372      375      380      381      387      393      395      396      399      399        China            40.18238,116.4142  九华国际会展中心C座, 顺沙路, Changping District, Beijing, ...    Beijing                                                        (, , )                      , Changping District, Beijing
2      Chongqing  30.05718  107.8740        6        9       27       57       75      110      132      147      182      211     247     300     337     366     389     411     426     428     468      486      505      518      529      537      544      551      553      555      560      567      572      573      575        China             30.05718,107.874          Longkong, Fengdu County, Chongqing, China  Chongqing                                                        (, , )                         , Fengdu County, Chongqing
3         Fujian  26.07783  117.9895        1        5       10       18       35       59       80       84      101      120     144     159     179     194     205     215     224     239     250      261      267      272      279      281      285      287      290      292      293      293      293      293      293        China            26.07783,117.9895                                       Sanming City     Fujian                          (Sanming City, Youxi County, Fujian)                 Sanming City, Youxi County, Fujian
4          Gansu  36.06110  103.8343        0        2        2        4        7       14       19       24       26       29      40      51      55      57      62      62      67      79      83       83       86       87       90       90       90       90       91       91       91       91       91       91       91        China             36.0611,103.8343                             Guangwumen Subdistrict      Gansu             (Guangwumen Subdistrict, Chengguan District, G...  Guangwumen Subdistrict, Chengguan District, Gansu

In [195]:
# Repeat steps for ROCS and city population datasets

rocs_df2['lat_long'] = rocs_df2.lat.map(str) + ',' + rocs_df2.long.map(str)
rocs_df2['city_county_state'] = rocs_df2['lat_long'].apply(city_county_state)

RateLimiter caught an error, retrying (0/2 tries). Called with (*('8.977778,38.799444',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests

KeyboardInterrupt:

In [186]:
city_pop_df['lat_long'] = city_pop_df.Latitude.map(str) + ',' + city_pop_df.Longitude.map(str)
city_pop_df['city_county_state'] = city_pop_df['lat_long'].apply(city_county_state)

RateLimiter caught an error, retrying (0/2 tries). Called with (*('-34.945,138.530556',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter caught an error, retrying (1/2 tries). Called with (*('-34.945,138.530556',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter swallowed an error after 2 retries. Called with (*('-34.945,138.530556',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter caught an error, retrying (0/2 tries). Called with (*('-37.009722,174.791667',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter caught an error, retrying (1/2 tries). Called with (*('-37.009722,174.791667',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests

RateLimiter swallowed an error after 2 retries. Called with (*('-37.009722,174.791667',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter caught an error, retrying (0/2 tries). Called with (*('-23.806667,133.902222',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter caught an error, retrying (1/2 tries). Called with (*('-23.806667,133.902222',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter swallowed an error after 2 retries. Called with (*('-23.806667,133.902222',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter caught an error, retrying (0/2 tries). Called with (*('-38.039444,144.469444',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests

RateLimiter caught an error, retrying (1/2 tries). Called with (*('-38.039444,144.469444',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter swallowed an error after 2 retries. Called with (*('-38.039444,144.469444',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter caught an error, retrying (0/2 tries). Called with (*('-17.948889,122.228333',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter caught an error, retrying (1/2 tries). Called with (*('-17.948889,122.228333',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter swallowed an error after 2 retries. Called with (*('-17.948889,122.228333',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests

RateLimiter caught an error, retrying (0/2 tries). Called with (*('-27.384167,153.1175',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter caught an error, retrying (1/2 tries). Called with (*('-27.384167,153.1175',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter swallowed an error after 2 retries. Called with (*('-27.384167,153.1175',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter caught an error, retrying (0/2 tries). Called with (*('-28.833889,153.5625',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter caught an error, retrying (1/2 tries). Called with (*('-28.833889,153.5625',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests

RateLimiter swallowed an error after 2 retries. Called with (*('-28.833889,153.5625',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter caught an error, retrying (0/2 tries). Called with (*('-35.306944,149.195',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter caught an error, retrying (1/2 tries). Called with (*('-35.306944,149.195',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter swallowed an error after 2 retries. Called with (*('-35.306944,149.195',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter caught an error, retrying (0/2 tries). Called with (*('-30.320556,153.116389',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests

RateLimiter caught an error, retrying (1/2 tries). Called with (*('-30.320556,153.116389',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter swallowed an error after 2 retries. Called with (*('-30.320556,153.116389',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter caught an error, retrying (0/2 tries). Called with (*('-43.489444,172.532222',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter caught an error, retrying (1/2 tries). Called with (*('-43.489444,172.532222',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter swallowed an error after 2 retries. Called with (*('-43.489444,172.532222',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests

RateLimiter caught an error, retrying (0/2 tries). Called with (*('-16.878056,145.748889',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter caught an error, retrying (1/2 tries). Called with (*('-16.878056,145.748889',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter swallowed an error after 2 retries. Called with (*('-16.878056,145.748889',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter caught an error, retrying (0/2 tries). Called with (*('-12.414722,130.876667',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter caught an error, retrying (1/2 tries). Called with (*('-12.414722,130.876667',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests

RateLimiter swallowed an error after 2 retries. Called with (*('-12.414722,130.876667',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter caught an error, retrying (0/2 tries). Called with (*('-45.929167,170.1975',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter caught an error, retrying (1/2 tries). Called with (*('-45.929167,170.1975',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter swallowed an error after 2 retries. Called with (*('-45.929167,170.1975',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests
RateLimiter caught an error, retrying (0/2 tries). Called with (*('-23.57,148.177778',), **{'language': 'en'}).
Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/extra/rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/osm.py", line 468, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/geopy/geocoders/base.py", line 373, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests

KeyboardInterrupt:

In [198]:
print('JHU: ', len(jhu_df), len(jhu_df['city_county_state'].unique()))

jhu_df['city_county_state'][78]

# print('ROCS: ', len(rocs_df2), len(rocs_df2['city_county_state'].unique()))
# print('City pop: ', len(city_pop_df), len(city_pop_df['city_county_state'].unique()))

JHU:  85 84

'Yokohama, , Kanagawa Prefecture'

In [ ]:
# merge city_pop_df, rocs_df2 on (city_county_state, country) -- then jhu_df after figuring
# out time series